site_name: Clases Métodos Numéricos 2025

theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo claro
  icon:
    logo: material/function-variant

nav:
  - Inicio: index.md
  - Códigos:
      - Newton-Raphson Segura: newtonRaphson_segura.md
      - Newton Simple: newton_simple.md
      - Newton-Raphson para Sistemas: newtonRaphson_sistema.md
      - Jacobiano: jacobian.md
  - Descarga:
      - Bisección: bisect.m
      - Épsilon de Máquina: epsilon_maquina.m
      - Jacobiano: jacobian.m
      - Newton-Raphson Segura: newtonRaphson_segura.m
      - Newton-Raphson para Sistemas: newtonRaphson_sistema.m
      - Newton Simple: newton_simple.m
      - Rootsearch: rootsearch.m

markdown_extensions:
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rilarfer
      name: GitHub rilarfer
    - icon: fontawesome/solid/user
      link: https://github.com/rilarfer/clases-mn-2025
      name: Proyecto en GitHub
  copyright:
    text: "© 2025 Ricardo Largaespada"
    